services:
  - type: web
    name: depsi-ticket-verifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x startup.sh && ./startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /var/data/tickets.db
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1