services:
  - type: web
    name: zelle-venmo-verifier
    env: python
    buildCommand: |
      pip install -r requirements-deploy.txt &&
      cd frontend &&
      npm install &&
      npm run build &&
      cd ..
    startCommand: gunicorn backend.api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: NODE_VERSION
        value: 18.17.0