services:
  - type: web
    name: depsi-ticket-verifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /var/data/tickets.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1