services:
  - type: web
    name: depsi-ticket-verifier
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "=== Checking system dependencies ==="
      if [ -d "/var/data" ]; then
        echo "✅ Persistent disk found at /var/data"
        ls -la /var/data/
      else
        echo "⚠️  Persistent disk not found at /var/data"
      fi
      echo "=== Python OCR alternatives available ==="
      python -c "import easyocr; print('✅ EasyOCR available')" 2>/dev/null || echo "❌ EasyOCR not available"
      python -c "import fitz; print('✅ PyMuPDF available')" 2>/dev/null || echo "❌ PyMuPDF not available"
      python -c "import pytesseract; print('✅ pytesseract available')" 2>/dev/null || echo "❌ pytesseract not available"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /var/data/tickets.db
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: FLASK_ENV
        value: production
      # Cloudflare R2 Storage Configuration
      - key: R2_ACCOUNT_ID
        sync: false  # Set this manually in Render dashboard
      - key: R2_BUCKET_NAME
        sync: false  # Set this manually in Render dashboard
      - key: R2_ACCESS_KEY_ID
        sync: false  # Set this manually in Render dashboard
      - key: R2_SECRET_ACCESS_KEY
        sync: false  # Set this manually in Render dashboard
      - key: R2_ENDPOINT
        sync: false  # Set this manually in Render dashboard
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1